
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-extensions-godaddy",
  "version": "1.0.0",
  "versions": {
    "@openai/agents-extensions-godaddy": "1.0.0"
  }
};

export default METADATA;
