
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents",
  "version": "0.4.11",
  "versions": {
    "@openai/agents": "0.4.11",
    "@openai/agents-core": "workspace:*",
    "@openai/agents-openai": "workspace:*",
    "@openai/agents-realtime": "workspace:*",
    "openai": "^6.20.0"
  }
};

export default METADATA;
