
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-openai",
  "version": "0.2.0",
  "versions": {
    "@openai/agents-openai": "0.2.0",
    "@openai/agents-core": "workspace:*",
    "openai": "^6"
  }
};

export default METADATA;
