
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-openai",
  "version": "0.0.11-D",
  "versions": {
    "@openai/agents-openai": "0.0.11-D",
    "@openai/agents-core": "workspace:*",
    "openai": "^5.0.1",
    "@openai/zod": "npm:zod@3.25.40 - 3.25.67"
  }
};

export default METADATA;
