
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-core",
  "version": "0.4.10",
  "versions": {
    "@openai/agents-core": "0.4.10",
    "openai": "^6.20.0"
  }
};

export default METADATA;
