
// This file is automatically generated

export const METADATA = {
  "name": "@chollier/agents-extensions",
  "version": "0.0.9",
  "versions": {
    "@chollier/agents-extensions": "0.0.9",
    "@openai/zod": "npm:zod@^3.25.40"
  }
};

export default METADATA;
