
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-realtime",
  "version": "0.13.4",
  "versions": {
    "@openai/agents-realtime": "0.13.4",
    "@openai/agents-core": "workspace:*"
  }
};

export default METADATA;
